"""empty message

Revision ID: d803ed69283f
Revises: 
Create Date: 2020-07-20 13:18:13.714547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd803ed69283f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AllWikiLinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wikiLink', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(length=50000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('settings', sa.Text(length=32500), nullable=True),
    sa.Column('tracking', sa.Text(length=32500), nullable=True),
    sa.Column('rank', sa.String(length=3), nullable=True),
    sa.Column('wikiLinks', sa.Text(length=32500), nullable=True),
    sa.Column('remainingLimit', mysql.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('wikipediaArticles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articleName', sa.String(length=200), nullable=True),
    sa.Column('articleDict', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikipediaArticles')
    op.drop_table('users')
    op.drop_table('AllWikiLinks')
    # ### end Alembic commands ###
